# Configuration file for the ansys FDTD simulation

#Layers configuration --> materials needs to be added in the base.fsp file directly
layers:

- name: downshifters
  material: "1.5"
  thickness: 0.1e-6
  nd: 1.5

- name: Anti-glare
  surface: true
  material: "1.7"
  thickness: 5e-6
  nd: 1.7
  sigma_rms: 0.07e-6 
  corr_length_x: 0.1e-6
  corr_length_y: 0.1e-6
  seed_process: 8
  delta: 0.005e-6

x_thickness: 15e-7
z_thickness: 10e-9
dipole_density_reference: 1e21   # [dipoles / m^3] typical value (not use)

#FDTD parameters

FDTD:
  dimension: "2D"           # "2D" or "3D"
  x: 0
  #y: will be determined dynamically in the build_strcuture.py script as function of the total thickness of the layers
  z: 0.0
  x_span: 1e-6
  #y_span: will be determined dynamically in the build_strcuture.py script as function of the total thickness of the layers
  z_span: 0

  Boundary:
    x_min: "Bloch" # indispensable using sweep angle
    x_max: "Bloch"
    y_min: "PML"
    y_max: "PML"
    z_min: "PML"
    z_max: "PML"

Source:
  lambda_min: 5e-07
  lambda_max: 5e-07
