# Configuration file for the ansys FDTD simulation


#Layers configuration --> materials needs to be added in the base.fsp file directly
layers:
  - name: silicon
    material: "Si (Silicon) - Palik"
    thickness: 3.0e-6

  - name: encap
    material: "SiO2 (Glass) - Palik"
    thickness: 1.0e-6

  - name: downshifters
    group: true
    matrix_material: "SiOxNy - 80%N"
    nanoparticle_material: "test2"
    thickness: 0.5e-6
    nanoparticle:
      radius: 5e-9
      density: 0.5   # filling factor (50%)

  - name: glass
    material: "SiO2 (Glass) - Palik"
    thickness: 1.0e-6

  - name: anti_glare
    material: "SiO2 (Glass) - Palik"
    thickness: 0.5e-6

x_thickness: 30e-9
z_thickness: 30e-9
dipole_density_reference: 1e21   # [dipoles / m^3] typical value

#FDTD parameters

FDTD:
  dimension: "2D"           # "2D" or "3D"
  x: 0
  #y: will be determined dynamically in the build_strcuture.py script as function of the total thickness of the layers
  z: 0.0
  x_span: 1e-6
  #y_span: will be determined dynamically in the build_strcuture.py script as function of the total thickness of the layers
  z_span: 0

  Boundary:
    x_min: "Periodic"
    x_max: "Periodic"
    y_min: "PML"
    y_max: "PML"
    z_min: "PML"
    z_max: "PML"

Source:
  lambda_min: 0.8e-6
  lambda_max: 1.4e-6

